In [1]:
import numpy as np
import pandas as pd
data=pd.read_excel("Ecommerce_Unclean_Project.xlsx")

In [4]:
data.head(5)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [43]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 61.5+ KB

In [44]:
data.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [45]:
data.shape

(524, 15)

In [46]:
  data.isnull()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
520,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
521,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
522,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
523,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [47]:
data.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [48]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
519    False
520    False
521    False
522    False
523    False
Length: 524, dtype: bool

In [49]:
data.duplicated().sum()

np.int64(11)

In [50]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()

np.int64(0)

In [51]:
data.shape

(513, 15)

In [52]:
data.replace(['N/A','NULL',''],np.nan,inplace=True)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [53]:
#Remove extra space
data=data.apply(lambda x: x.str.strip() if x.dtype ==
                'object' else x)

In [54]:
data['Customer_Name']=data['Customer_Name'].str.title()
data['City']=data['City'].str.title()
data['State']=data['State'].str.title()

In [55]:
#keep only valide email records
data=data[data['Email'].str.contains('@',na=False)]

In [56]:
#Converte date culumn
data['Order_Date']=pd.to_datetime(data['Order_Date'],errors='coerce')
data['Delivery_date']=pd.to_datetime(data['Delivery_Date'],errors='coerce')

C:\Users\HP\AppData\Local\Temp\ipykernel_19304\123557584.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['Order_Date']=pd.to_datetime(data['Order_Date'],errors='coerce')

In [57]:
cols=["Qty","Unit_Price","Discount"]
for c in cols:
    data[c]=pd.to_numeric(data[c],errors="coerce")

In [58]:
data=data[data["Qty"]>0]

In [5]:
data["Discount"]=data["Discount"].fillna(0)
data["Phone"]=data["Phone"].fillna("Unknown")
data["Delivery_Date"]=data["Delivery_Date"].fillna(data["Order_Date"])

In [21]:
data["Sales"]=data["Qty"]*data["Unit_Price"]
data
#data["Net_Amount"]=data["Sales"]-(data["Sales"]*data["Discount"]/100)
#data["Profit"]=data["Net_Amount"]*0.20
#data["Month"]=data["Order_Date"].dt.month_name()
#data["Year"]=data["Order_Date"].dt.year()
#data["Weekday"]=data["Order_Date"].dt.day_name()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0,UPI,Pending,03-07-2025,7996.0
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025,24995.0
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025,5997.0
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474.0,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025,NaN
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620.0,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0,Card,Returned,27-02-2025,39996.0
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025,2998.0
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025,NaN
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025,2997.0
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025,2997.0

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          524 non-null    object
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       524 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  524 non-null    str
 15  Sales          414 non-null    float64
dtypes: float64(3), object(2), str(11)
memory usage: 65.6+ KB

In [13]:
data.isnull().sum()

Order_ID           0
Order_Date         0
Customer_Name      0
Email              0
Phone              0
City               0
State              0
Product            0
Category           0
Qty               67
Unit_Price        53
Discount           0
Payment_Mode       0
Order_Status       0
Delivery_Date      0
Sales            110
dtype: int64

In [14]:
data.describe()

              Qty   Unit_Price         Sales
count  457.000000   471.000000    414.000000
mean     2.800875  3168.639066   9436.577295
std      1.963974  2969.682209  12333.566864
min     -1.000000   499.000000  -9999.000000
25%      1.000000   999.000000   1998.000000
50%      3.000000  1999.000000   4999.000000
75%      5.000000  4999.000000  12995.000000
max      5.000000  9999.000000  49995.000000

In [15]:
data.duplicated().sum()

np.int64(11)

In [24]:
data.to_excel("Clean Ecommerce.xlsx",index=False)

In [28]:
data.to_csv("Clean Ecommerce1.xlsx",index=False)

In [31]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
pip install pymysql

Requirement already satisfied: pymysql in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [59]:
from sqlalchemy import create_engine

In [56]:
engine=create_engine("mysql+pymysql://root:Satya123@localhost/ecommerce")

In [57]:
data.to_sql(
    name='orders',
    con=engine,
    if_exists='replace',
    index=False
)

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [58]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.1)
Requirement already satisfied: openpyxl in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [65]:
username="root"
password=""
host="localhost"
database_name="ecommerce"
engine=create_engine("mysql+pymysql://root:""@localhost/ecommerce")

In [3]:
data.to_sql(
    name="orders",
    con=engine,
    if_exists="replace",
    index=False
)

NameError: name 'engine' is not defined

In [4]:
import urllib.parse
from sqlalchemy import create_engine

username = "root"
# This safely encodes characters like @, #, $, or /
password = urllib.parse.quote_plus("Satya123@")  
host = "localhost"
database_name = "ecommerce"

# Rebuild the engine connection
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}/{database_name}")

In [5]:
data.to_sql(
    name="orders",
    con=engine,
    if_exists="replace",
    index=False
)

524